### ISSUE TITLE
选中状态恢复

### ISSUE THREAD

**Issue by phoenix-ke** [Wongxd/skuLib#1]
你好，首先十分感谢你的分享，刚好最近也在开发sku商品选择功能，对此我这边还有一个需求，请问下一次打开弹框的时候如何恢复上一次选中的状态呢？

**Comment by Wongxd** [comment]
我没有这个需求，所以没有实现它。你可以在选中后保存当前选中的组合，然后在组合选中框初始化后，为其赋值成上次选中组合。

**Comment by Wongxd** [comment]
实现你要的功能了。
